server:
  port: 8888
database:
  url: jdbc:mysql://47.98.128.88:3306/supplies?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Hongkong
  username: root
  password: kindy0916
spring:
  datasource:
    url: ${database.url}
    username: ${database.username}
    password: ${database.password}
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    default-property-inclusion: non_null
pagehelper:
  helperDialect: mysql  #设置数据库
  reasonable: true  #分页合理化参数pageNum<=0 时会查询第一页，pageNum>pages（超过总数时），会查询最后一页
  page-size-zero: true  #pageSize=0 每页显示条数为0 就会查询出全部的结果（但是返回结果仍然是 Page 类型）
  supportMethodsArguments: true
  params: count=countSql
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapping/*.xml
